### ISSUE TITLE
Build issue for android arm64 IL2CPP

### ISSUE THREAD

**Issue by mandelmonkey** [mapbox/mapbox-unity-sdk#1486]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
2019.2.5f1
  * Scripting Runtime Version: 
dot net 4
  * Scripting Backend: 
c#
  * IL2CPP
24
* Mapbox SDK version: 
2.1.0
* The platform you're building to:
android
* A description of what you're trying to do:
Build the app for android with Arm64 and 

* Steps to recreate the bug if appropriate:
create a blank project, add the mapbox sdk and try to build for android with arm64 and IL2CPPselected

* Links to your logs are also helpful: 

```

	Time Compile: 11495 milliseconds Il2CppTypeDefinitions.c
	Time Compile: 9318 milliseconds Il2CppAttributes.cpp
	Time Compile: 2749 milliseconds UnityEngine.CoreModule1.cpp
	Time Compile: 1696 milliseconds Il2CppCompilerCalculateTypeValues2.cpp
	Time Compile: 1628 milliseconds Il2CppCompilerCalculateTypeValues1.cpp
	Time Compile: 1050 milliseconds mscorlib_CodeGen.c
	Time Compile: 955 milliseconds Il2CppCompilerCalculateTypeValues3.cpp
	Time Compile: 789 milliseconds Il2CppCompilerCalculateTypeValuesTable.cpp
	Time Compile: 650 milliseconds System.Xml_CodeGen.c
	Time Compile: 640 milliseconds System_CodeGen.c
Total compilation time: 12333 milliseconds.
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: /Applications/Unity/Hub/Editor/2019.2.5f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ @"/var/folders/rp/f7xqr7490tb5_98n7cjvxsx80000gn/T/tmpAg1cec.tmp" -o "/Users/chris/Documents/Takara/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/linkresult_D631B25777D1509CE811281F3D1212DE/libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "/Applications/Unity/Hub/Editor/2019.2.5f1/PlaybackEngines/AndroidPlayer/NDK/platforms/android-16/arch-arm" -gcc-toolchain "/Applications/Unity/Hub/Editor/2019.2.5f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "/Applications/Unity/Hub/Editor/2019.2.5f1/PlaybackEngines/AndroidPlayer/NDK/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a" -lgnustl_static -latomic -llog -rdynamic -fuse-ld=gold

/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp1.cpp:20345: error: undefined reference to 'DeepLinkReceiverIsAlive'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp1.cpp:20345: error: undefined reference to 'DeepLinkReceiverIsAlive'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21969: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21969: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25819: error: undefined reference to 'StartWorldTrackingSessionWithOptions'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25908: error: undefined reference to 'PauseSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26004: error: undefined reference to 'CapturePixelData'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25950: error: undefined reference to 'GetVideoTextureHandles'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25994: error: undefined reference to 'SetCameraNearFar'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26014: error: undefined reference to 'SessionAddUserAnchor'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26029: error: undefined reference to 'SessionRemoveUserAnchor'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21073: error: undefined reference to 'GetBlendShapesInfo'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21073: error: undefined reference to 'GetBlendShapesInfo'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21743: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21743: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21851: error: undefined reference to 'IsARKitSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21851: error: undefined reference to 'IsARKitSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21969: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25918: error: undefined reference to 'HitTest'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25931: error: undefined reference to 'GetLastHitTestResult'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25838: error: undefined reference to 'StartSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25687: error: undefined reference to 'unity_CreateNativeARSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25718: error: undefined reference to 'session_SetSessionCallbacks'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25740: error: undefined reference to 'session_SetPlaneAnchorCallbacks'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25762: error: undefined reference to 'session_SetUserAnchorCallbacks'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25784: error: undefined reference to 'session_SetFaceAnchorCallbacks'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25800: error: undefined reference to 'StartWorldTrackingSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25819: error: undefined reference to 'StartWorldTrackingSessionWithOptions'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25838: error: undefined reference to 'StartSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25857: error: undefined reference to 'StartSessionWithOptions'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25876: error: undefined reference to 'StartFaceTrackingSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25895: error: undefined reference to 'StartFaceTrackingSessionWithOptions'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25908: error: undefined reference to 'PauseSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25918: error: undefined reference to 'HitTest'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25931: error: undefined reference to 'GetLastHitTestResult'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25950: error: undefined reference to 'GetVideoTextureHandles'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25961: error: undefined reference to 'GetAmbientIntensity'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25972: error: undefined reference to 'GetTrackingQuality'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25983: error: undefined reference to 'GetARPointCloud'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25994: error: undefined reference to 'SetCameraNearFar'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26004: error: undefined reference to 'CapturePixelData'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26014: error: undefined reference to 'SessionAddUserAnchor'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26029: error: undefined reference to 'SessionRemoveUserAnchor'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25687: error: undefined reference to 'unity_CreateNativeARSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25983: error: undefined reference to 'GetARPointCloud'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25800: error: undefined reference to 'StartWorldTrackingSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25857: error: undefined reference to 'StartSessionWithOptions'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25895: error: undefined reference to 'StartFaceTrackingSessionWithOptions'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25876: error: undefined reference to 'StartFaceTrackingSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25961: error: undefined reference to 'GetAmbientIntensity'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25972: error: undefined reference to 'GetTrackingQuality'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21743: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21851: error: undefined reference to 'IsARKitSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21969: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)


   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: /Applications/Unity/Hub/Editor/2019.2.5f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ @"/var/folders/rp/f7xqr7490tb5_98n7cjvxsx80000gn/T/tmpAg1cec.tmp" -o "/Users/chris/Documents/Takara/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/linkresult_D631B25777D1509CE811281F3D1212DE/libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "/Applications/Unity/Hub/Editor/2019.2.5f1/PlaybackEngines/AndroidPlayer/NDK/platforms/android-16/arch-arm" -gcc-toolchain "/Applications/Unity/Hub/Editor/2019.2.5f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "/Applications/Unity/Hub/Editor/2019.2.5f1/PlaybackEngines/AndroidPlayer/NDK/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a" -lgnustl_static -latomic -llog -rdynamic -fuse-ld=gold

/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp1.cpp:20345: error: undefined reference to 'DeepLinkReceiverIsAlive'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp1.cpp:20345: error: undefined reference to 'DeepLinkReceiverIsAlive'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21969: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21969: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25819: error: undefined reference to 'StartWorldTrackingSessionWithOptions'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25908: error: undefined reference to 'PauseSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26004: error: undefined reference to 'CapturePixelData'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25950: error: undefined reference to 'GetVideoTextureHandles'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25994: error: undefined reference to 'SetCameraNearFar'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26014: error: undefined reference to 'SessionAddUserAnchor'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:26029: error: undefined reference to 'SessionRemoveUserAnchor'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21073: error: undefined reference to 'GetBlendShapesInfo'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21073: error: undefined reference to 'GetBlendShapesInfo'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21743: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21743: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21851: error: undefined reference to 'IsARKitSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21851: error: undefined reference to 'IsARKitSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:21969: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25918: error: undefined reference to 'HitTest'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25931: error: undefined reference to 'GetLastHitTestResult'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25838: error: undefined reference to 'StartSession'
/Users/chris/Documents/Takara/Temp/StagingArea/Il2Cpp/il2cppOutput/Assembly-CSharp9.cpp:25687: error: undefined reference to 'unity_CreateNativeAR<message truncated>
```

**Comment by cheesemichael** [comment]
Hi, while we wait for the AR Kit fix. you can do this

1) delete UnityARKitPlugin folder
2) delete UnityARInterface/ARRemote folder
3)delete UnityARInterface/Examples/ARFocusSquare folder
4)delete UnityARInterface/Scripts/ARKitinterface.cs

build again...


** to reverse these steps, import the mapbox-unity-sdk_v2.1.1 again
