### ISSUE TITLE
Mapbox SDK Wont Build to Mobile With Experimental Scripting Runtime Version .net 4.6

### ISSUE THREAD

**Issue by cjwhite7** [mapbox/mapbox-unity-sdk#236]
Building to iOS won't work with Mapbox SDK using Scripting Runtime Version .net 4.6 

Errors below

Error 1
IL2CPP error for method 'System.Void System.Data.ConstraintCollection::Clear()' in assembly '/Users/chriswhite/MapboxTest/Temp/StagingArea/Data/Managed/System.Data.dll'
Additional information: Build a development build for more information. Exception of type 'System.Exception' was thrown.

Error 2 
Failed running /Applications/Unity/Unity.app/Contents/il2cpp/build/il2cppcore/il2cppcore.dll --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="net45" --map-file-parser="/Applications/Unity/Unity.app/Contents/Tools/MapFileParser/MapFileParser" --assembly="/Users/chriswhite/MapboxTest/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll" --assembly="/Users/chriswhite/MapboxTest/Temp/StagingArea/Data/Managed/Facebook.Unity.Settings.dll" --assembly="/Users/chriswhite/MapboxTest/Temp/StagingArea/Data/Managed/UnityEngine.dll" --assembly="/Users/chriswhite/MapboxTest/Temp/StagingArea/Data/Managed/Facebook.Unity.Android.dll" --assembly="/Users/chriswhite/MapboxTest/Temp/StagingArea/Data/Managed/Facebook.Unity.IOS.dll" --assembly="/Users/chriswhite/MapboxTest/Temp/StagingArea/Data/Managed/System.dll" --generatedcppdir="/Users/chriswhite/MapboxTest/Temp/il2cppOutput/il2cppOutput" 

stdout:
IL2CPP error for method 'System.Void System.Data.ConstraintCollection::Clear()' in assembly '/Users/chriswhite/MapboxTest/Temp/StagingArea/Data/Managed/System.Data.dll'
Additional information: Build a development build for more information. Exception of type 'System.Exception' was thrown.
il2cpp.exe didn't catch exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at Unity.IL2CPP.Extensions.WithoutModifiers(TypeReference typeReference) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/Extensions.cs:line 197
   at Unity.IL2CPP.Naming.TypeNaming.ForVariable(INamingService naming, TypeReference variableType) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/Naming/TypeNaming.cs:line 55
   at Unity.IL2CPP.ExceptionSupport.PushExceptionOnStack(Stack`1 valueStack, TypeReference catchType) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/ExceptionSupport.cs:line 1005
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/MethodBodyWriter.cs:line 302
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/MethodBodyWriter.cs:line 376
   at Unity.IL2CPP.MethodBodyWriter.Generate() in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/MethodBodyWriter.cs:line 233
   at Unity.IL2CPP.MethodWriter.WriteMethodWithMetadataInitialization(CppCodeWriter writer, String methodSignature, String methodFullName, Action`3 writeMethodBody, String uniqueIdentifier) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/MethodWriter.cs:line 169
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(CppCodeWriter writer, MethodReference method, IMethodCollector methodCollector, IMethodVerifier methodVerifier, ISourceAnnotationWriter sourceAnnotationWriter, IIcallMappingService icallMapping, VTableBuilder vtableBuilder) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/MethodWriter.cs:line 72
   at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles(NPath outputDirectory, SourceWritingContext sourceWritingContext, String fileName, IEnumerable`1 typeList, IMethodCollector methodCollector, IInteropDataCollector interopDataCollector, Boolean writeMarshalingDefinitions) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/SourceWriter.cs:line 289
   at Unity.IL2CPP.SourceWriter.Write(NPath outputDir, SourceWritingContext sourceWritingContext, ReadOnlyCollection`1 assemblyDefinitions, IMethodCollector methodCollector, IInteropDataCollector interopDataCollector) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/SourceWriter.cs:line 64
   at Unity.IL2CPP.AssemblyConverter.Apply() in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/AssemblyConverter.cs:line 160
   at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/Unity.IL2CPP/AssemblyConverter.cs:line 56
   at il2cpp.Program.DoRun(String[] args) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/il2cpp/Program.cs:line 204
   at il2cpp.Program.Run(String[] args) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/il2cpp/Program.cs:line 103
   at il2cpp.Program.Main(String[] args) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/il2cpp/Program.cs:line 80
stderr:

Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at Unity.IL2CPP.Extensions.WithoutModifiers(TypeReference typeReference)
   at Unity.IL2CPP.Naming.TypeNaming.ForVariable(INamingService naming, TypeReference variableType)
   at Unity.IL2CPP.ExceptionSupport.PushExceptionOnStack(Stack`1 valueStack, TypeReference catchType)
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node)
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node)
   at Unity.IL2CPP.MethodBodyWriter.Generate()
   at Unity.IL2CPP.MethodWriter.WriteMethodWithMetadataInitialization(CppCodeWriter writer, String methodSignature, String methodFullName, Action`3 writeMethodBody, String uniqueIdentifier)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(CppCodeWriter writer, MethodReference method, IMethodCollector methodCollector, IMethodVerifier methodVerifier, ISourceAnnotationWriter sourceAnnotationWriter, IIcallMappingService icallMapping, VTableBuilder vtableBuilder)
   at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles(NPath outputDirectory, SourceWritingContext sourceWritingContext, String fileName, IEnumerable`1 typeList, IMethodCollector methodCollector, IInteropDataCollector interopDataCollector, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriter.Write(NPath outputDir, SourceWritingContext sourceWritingContext, ReadOnlyCollection`1 assemblyDefinitions, IMethodCollector methodCollector, IInteropDataCollector interopDataCollector)
   at Unity.IL2CPP.AssemblyConverter.Apply()
   at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
   at Program.Main(String[] args)

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunProgram(Program, String, String, String, CompilerOutputParserBase) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:128)
UnityEditorInternal.Runner:RunNetCoreProgram(String, String, String, CompilerOutputParserBase, Action`1) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:79)
UnityEditorInternal.IL2CPPBuilder:RunIl2CppWithArguments(List`1, Action`1, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:322)
UnityEditorInternal.IL2CPPBuilder:ConvertPlayerDlltoCpp(ICollection`1, String, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:305)
UnityEditorInternal.IL2CPPBuilder:Run() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:151)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:34)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Error 3 
Exception: /Applications/Unity/Unity.app/Contents/il2cpp/build/il2cppcore/il2cppcore.dll did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:130)
UnityEditorInternal.Runner.RunNetCoreProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:79)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:322)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (System.Collections.Generic.ICollection`1[T] userAssemblies, System.String outputDirectory, System.String workingDirectory) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:305)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:151)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry, System.Boolean debugBuild) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:34)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport buildReport) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:733)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport buildReport) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:596)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessorSettings postProcessorSettings, UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:555)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:37)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:271)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by david-rhodes** [comment]
The 4.6 scripting runtime is `experimental`, so I would expect issues. I don't see anything here that points directly to Mapbox, so I would just assume it's a generic bug associated with the runtime. That said, I just tested a 4.6 development build in Unity 2017.1 with the vanilla SDK project and everything worked as expected. 

Maybe try a development build?

**Comment by cjwhite7** [comment]
Hi @david-rhodes, thanks for taking a look. The only reason we know it is mapbox is because we used the experimental for a while and it built fine to mobile. Only after we added mapbox did we get the compile error.

**Comment by david-rhodes** [comment]
@cjwhite7 Which scene are you trying to test? What version of Unity? I just tested a release build and it also worked fine for me with 2017.1.

Unfortunately, we cannot guarantee that C# calls in our SDK will be compatible with an experimental scripting runtime, as we know nothing of how Unity's internal IL2CPP system works. This sounds like a good candidate for a Unity bug report, however.
